{% if cookiecutter.use_mux == "y" -%}
server:
  listen: 0.0.0.0:4201
{%- endif %}


{% if cookiecutter.use_postgresql == "y" -%}
database:
  host: localhost
  port: 5432
  user: test
  password: test
  name: test
{%- endif %}

